# -*- coding: utf-8 -*-
"""Program1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q2U5yVeVn9tOvUh7H0xJ08AxtkyHyQIr
"""

import pandas as pd
import numpy as np
import re
import nltk

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,precision_score,recall_score,f1_score

true_df = pd.read_csv('/content/True.csv')
fake_df = pd.read_csv('/content/Fake.csv')
manual_df = pd.read_csv('/content/manual_testing.csv')

"""### **Load** **Datasets**"""

true_df.head()

fake_df.head()

manual_df.head()

fake_df.shape, true_df.shape,manual_df.shape

fake_df.columns,true_df.columns,manual_df.columns

fake_df.isnull().sum()

true_df.isnull().sum()

"""# Add Class Label to Fake Dataset"""

manual_df.isnull().sum()

true_df.describe()

fake_df["class"] = 0   # Fake News
true_df["class"] = 1   # True News

"""# Combine True & Fake Datasets"""

news_df = pd.concat([true_df, fake_df], axis=0)
news_df.reset_index(drop=True, inplace=True)
print(news_df)

"""Data Cleaning (Text Preprocessing)
# Define Cleaning Function
"""

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\W', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

"""# Apply Cleaning"""

news_df["text"] = news_df["text"].apply(clean_text)
manual_df["text"] = manual_df["text"].apply(clean_text)
print(news_df)
print(manual_df)

"""Feature Selection

# We will use only text (best for fake news detection).
"""

X = news_df["text"]
y = news_df["class"]

"""# Train–Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

"""# Convert Text to Numbers (TF-IDF)"""

vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

"""# Train AI Model (Logistic Regression)"""

model = LogisticRegression()
model.fit(X_train_tfidf, y_train)

model.coef_

"""# Model Evaluation"""

y_pred = model.predict(X_test_tfidf)

log_reg_acc=print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

"""Manual Testing Dataset (Your 3rd Dataset)
# Prepare Manual Test Data
"""

manual_text = vectorizer.transform(manual_df["text"])
manual_pred = model.predict(manual_text)
print(manual_pred)

"""# Compare Predictions"""

manual_df["Predicted_Class"] = manual_pred
print(manual_df[["text", "class", "Predicted_Class"]])

"""# Accuracy on Manual Testing"""

print("Manual Test Accuracy:",
      accuracy_score(manual_df["class"], manual_pred))

"""# GRAPH 1: Class Distribution (Fake vs Real News)"""

import matplotlib.pyplot as plt

# Count class values
class_counts = news_df["class"].value_counts()

plt.figure(figsize=(6,4))
plt.bar(["Fake News", "Real News"], class_counts)
plt.xlabel("News Type")
plt.ylabel("Number of Articles")
plt.title("Class Distribution of Fake and Real News")
plt.show()

"""# GRAPH 2: Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Fake", "Real"],
            yticklabels=["Fake", "Real"])
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Confusion Matrix")
plt.show()

"""# GRAPH 3: Model Accuracy"""

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

plt.figure(figsize=(5,4))
plt.bar(["Model Accuracy"], [accuracy], color="green")
plt.ylim(0, accuracy + 0.15) # Changed max(accuracies) to accuracy
plt.ylabel("Accuracy")
plt.title("Fake News Detection Model Accuracy")
plt.show()

"""# GRAPH 4:Histogram of Fake and Real News"""

plt.hist(news_df['class'], bins=2 ,rwidth=0.5)
plt.xlabel("News Class (0=Fake, 1=Real)")
plt.ylabel("Frequency")
plt.title("Histogram of Fake and Real News")
plt.show()

"""# **GRAPH 5:Manual Testing Prediction Results**



"""

import matplotlib.pyplot as plt

# Transform text using trained vectorizer
manul_vec = vectorizer.transform(manual_df['text'])

# Predict using trained model
manual_df['Predicted_Class'] = model.predict(manul_vec)

# Bar graph of predictions
manual_df['Predicted_Class'].value_counts().rename(
    index={0: 'Fake News', 1: 'True News'}
).plot(kind='bar')

plt.xlabel("Predicted Class")
plt.ylabel("Count")
plt.title("Manual Testing Prediction Results")
plt.show()

"""# **Graph 6:Pie Chart of Fake vs Real News Distribution**"""

counts = news_df['class'].value_counts()

# Pie chart
plt.pie(counts, labels=['Real News', 'Fake News'], autopct='%1.1f%%')
plt.title("Pie Chart of Fake vs Real News Distribution")
plt.show()

"""#METHOD 1: **SVM Model Training**"""

from sklearn.svm import LinearSVC

svm_model = LinearSVC()
svm_model.fit(X_train_tfidf, y_train)

"""# Final prediction result using SVM METHOD"""

y_pred = svm_model.predict(X_test_tfidf)

"""# **Model Evaluation using SVM METHOD**"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

svm_acc=print("Accuracy:", accuracy_score(y_test, y_pred))
cmsvm=print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
cmsvm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cmsvm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Fake", "Real"],
            yticklabels=["Fake", "Real"])
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Confusion Matrix")
plt.show()

"""#**METHOD 2: Random Forest Classifier Code**"""

from sklearn.ensemble import RandomForestClassifier

"""# Train Model"""

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf_model.fit(X_train_tfidf, y_train)

"""# Prediction"""

rf_pred = rf_model.predict(X_test_tfidf)

"""# Evaluation"""

from sklearn.metrics import accuracy_score, classification_report

rf_acc=print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print(classification_report(y_test, rf_pred))
cmrf=print("confusion_matrix:",confusion_matrix(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns

cmrf = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cmrf, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Fake", "Real"],
            yticklabels=["Fake", "Real"])
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Confusion Matrix")
plt.show()

"""# **Model 3:KNN**"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Create KNN model
knn_model = KNeighborsClassifier(
    n_neighbors=5,
    metric='cosine'   # works better with TF-IDF
)

#Train (fit) the model
knn_model.fit(X_train_tfidf, y_train)


#Make predictions
knn_pred = knn_model.predict(X_test_tfidf)

#Evaluate the model
knn_accuracy = accuracy_score(y_test, knn_pred)

print("KNN Accuracy:", knn_accuracy)
cmmknn=print("\nConfusion Matrix:\n", confusion_matrix(y_test, knn_pred))
print("\nClassification Report:\n", classification_report(y_test, knn_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns

cmmknn = confusion_matrix(y_test, knn_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cmmknn, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Fake", "Real"],
            yticklabels=["Fake", "Real"])
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.title("Confusion Matrix")
plt.show()

"""# **#COMPARE 3 MODELS ACCURACY**"""

import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

# Recalculate accuracies since previous assignments were incorrect (assigned None from print function)

# Logistic Regression Accuracy
y_pred_log_reg = model.predict(X_test_tfidf)
log_reg_acc = accuracy_score(y_test, y_pred_log_reg)

# SVM Accuracy
y_pred_svm = svm_model.predict(X_test_tfidf)
svm_acc = accuracy_score(y_test, y_pred_svm)

# Random Forest Accuracy (rf_pred is already available from previous execution)
rf_acc = accuracy_score(y_test, rf_pred)

#KNN
knn_pred = knn_model.predict(X_test_tfidf)
knn_accuracy = accuracy_score(y_test, knn_pred)



models = ['Logistic Regression', 'SVM', 'Random Forest','KNN']
accuracies = [log_reg_acc, svm_acc, rf_acc,knn_accuracy]

# Plot bar graph
plt.figure(figsize=(9, 5))
bars = plt.bar(models, accuracies, color=['skyblue', 'lightgreen', 'salmon','darkblue'])

# Add accuracy values on top of bars
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height,
             f'{height:.4f}', ha='center', va='bottom')

plt.xlabel('Models')
plt.ylabel('Accuracy')
plt.title('Accuracy Comparison of ML Models')
plt.ylim(0, max(accuracies) + 0.15)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()

# ==============================
# DYNAMIC FAKE NEWS PREDICTION
# ==============================

def predict_news(news_text):
    # Clean the input text
    news_text = news_text.lower()

    # Convert text into TF-IDF vector
    news_vector = vectorizer.transform([news_text])

    # Predict using trained SVM model
    prediction = model.predict(news_vector)

    # Print result
    if prediction[0] == 0:
        print("\n This is FAKE News")
    else:
        print("\n This is REAL News")


# Take input from user
user_input = input("Enter a news article: ")

predict_news(user_input)

# ==============================
# SIMPLE TRUE / FAKE PREDICTION
# ==============================

def predict_news(news_text):

    # Clean text same way as training
    news_text = news_text.lower()

    # Convert to TF-IDF
    news_vector = vectorizer.transform([news_text])

    # Predict using SVM (best model)
    prediction = svm_model.predict(news_vector)

    # Print only result
    if prediction[0] == 0:
        print("FAKE NEWS")
    else:
        print("TRUE NEWS")


# Take input
user_input = input("Enter news article: ")

predict_news(user_input)